import type { Metadata } from "next";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import NextAuthWrapper from "@/library/next.auth.wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <AntdRegistry>
                    <NextAuthWrapper>
                        {children}
                    </NextAuthWrapper>
                </AntdRegistry>
            </body>
        </html>
    );
}
